FROM    alpine:latest

LABEL   author="Joss Bird" maintainer="joss@disparity.host"

LABEL   org.opencontainers.image.source="https://github.com/slack69/hosting-node-containers"

RUN     apk add --update --no-cache ca-certificates curl git jq wget